version: '2'
services:
  kafka:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - SERVICE_NAME=kafka
      - SERVICE_9092_NAME=kafka
      - ADVERTISED_HOST=kafka.service.consul
      - ADVERTISED_PORT=9092

  mongo:
    image: mongo:3.2
    ports:
      - "27017:27017"
    environment:
      - SERVICE_NAME=mongodb
      - SERVICE_27017_NAME=mongodb
    volumes:
      - ./airfinity_dbs/mongo:/data/db
  
  neo4j:
    image: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./airfinity_dbs/neo4j/data:/data
